import { IData } from './interface/interface';

export const data: IData[] = [
  { name: 'John', age: 25, genre: 'male' },
  { name: 'Emma', age: 30, genre: 'female' },
  { name: 'Michael', age: 42, genre: 'male' },
  { name: 'Sophia', age: 19, genre: 'female' },
  { name: 'William', age: 36, genre: 'male' },
  { name: 'Olivia', age: 28, genre: 'female' },
  { name: 'James', age: 39, genre: 'male' },
  { name: 'Ava', age: 22, genre: 'female' },
  { name: 'Benjamin', age: 33, genre: 'male' },
  { name: 'Mia', age: 31, genre: 'female' },
  { name: 'Jacob', age: 27, genre: 'male' },
  { name: 'Lily', age: 24, genre: 'female' },
  { name: 'Ethan', age: 38, genre: 'male' },
  { name: 'Emily', age: 29, genre: 'male' },
  { name: 'Alexander', age: 35, genre: 'male' },
  { name: 'Sofia', age: 26, genre: 'female' },
  { name: 'Daniel', age: 41, genre: 'male' },
  { name: 'Charlotte', age: 23, genre: 'female' },
  { name: 'Matthew', age: 37, genre: 'male' },
  { name: 'Harper', age: 32, genre: 'male' },
  { name: 'Henry', age: 34, genre: 'male' },
  { name: 'Grace', age: 21, genre: 'male' },
  { name: 'Jackson', age: 40, genre: 'male' },
  { name: 'Chloe', age: 20, genre: 'female' },
  { name: 'Sebastian', age: 43, genre: 'male' },
  { name: 'Abigail', age: 18, genre: 'female' },
  { name: 'David', age: 45, genre: 'male' },
  { name: 'Elizabeth', age: 17, genre: 'male' },
  { name: 'Joseph', age: 44, genre: 'male' },
  { name: 'Ella', age: 16, genre: 'male' },
  { name: 'Daniel', age: 47, genre: 'male' },
  { name: 'Avery', age: 15, genre: 'male' },
  { name: 'Christopher', age: 48, genre: 'male' },
  { name: 'Scarlett', age: 14, genre: 'female' },
];
